// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC19slrPyAW91cr3wBiB9FMj8auvmF_F8U',
    appId: '1:11774536487:web:b72b251affd1ada65d5702',
    messagingSenderId: '11774536487',
    projectId: 'lndr-24452',
    authDomain: 'lndr-24452.firebaseapp.com',
    storageBucket: 'lndr-24452.firebasestorage.app',
    measurementId: 'G-C0PZ05CKM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt-1QudUexNxhDjLKXkv970kfRpn2XT4o',
    appId: '1:11774536487:android:1eaa8216d7ee03375d5702',
    messagingSenderId: '11774536487',
    projectId: 'lndr-24452',
    storageBucket: 'lndr-24452.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3XHYUcY4a_GYdrs6pGQ-WH2IYYtDu79s',
    appId: '1:11774536487:ios:cfcb2d08925492805d5702',
    messagingSenderId: '11774536487',
    projectId: 'lndr-24452',
    storageBucket: 'lndr-24452.firebasestorage.app',
    iosBundleId: 'com.example.lndr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC19slrPyAW91cr3wBiB9FMj8auvmF_F8U',
    appId: '1:11774536487:web:6d164ca2fd05ca645d5702',
    messagingSenderId: '11774536487',
    projectId: 'lndr-24452',
    authDomain: 'lndr-24452.firebaseapp.com',
    storageBucket: 'lndr-24452.firebasestorage.app',
    measurementId: 'G-3BH2PPCC09',
  );
}
